
# redis for job queue
redis:
  image: redis
  container_name: cache
  expose: 
    - 6379

# our node express app
app:
  container_name: my-subscribe-demo-app
  build: ./
  volumes: 
    - ./:/var/www/app
  ports:
    - 5000:5000
  links: 
    - redis
  environment:
    - PORT=5000
    - HOST=0.0.0.0
    - REDIS_PORT=6379
    - REDIS_HOST=cache
  command: 
    sh -c 'npm run build && npm start'